/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // For now, we'll use autogenerated sidebar until content is migrated
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Vision & Strategy',
      items: [
        'vision-strategy/executive-summary',
        'vision-strategy/project-vision',
        'vision-strategy/success-factors',
        'vision-strategy/current-status',
      ],
    },
    {
      type: 'category',
      label: 'Organization',
      items: [
        'organization/organizational-structure',
        'organization/governance',
        'organization/team-roles',
        'organization/legal-framework',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/restoration-methodology',
        'operations/technology-integration',
        'operations/challenges-solutions',
      ],
    },
    {
      type: 'category',
      label: 'Business',
      items: [
        'business/business-model',
        'business/financial-projections',
        'business/funding-strategy',
      ],
    },
    {
      type: 'category',
      label: 'Growth',
      items: [
        'growth/expansion-strategy',
        'growth/site-selection',
        'growth/adaptive-timeline',
        'growth/operations-action-plan',
        'growth/tiny-house-infrastructure',
      ],
    },
    {
      type: 'category',
      label: 'Performance',
      items: [
        'performance/risk-assessment',
        'performance/kpis',
      ],
    },
    {
      type: 'category',
      label: 'Engagement',
      items: [
        'engagement/marketing-communications',
      ],
    },
    {
      type: 'category',
      label: 'Learning',
      items: [
        'learning/case-studies',
      ],
    },
    {
      type: 'category',
      label: 'Restoration Playbook',
      items: [
        'restoration-playbook/README',
        {
          type: 'category',
          label: 'Biodiversity',
          items: [
            'restoration-playbook/biodiversity/restoration-playbook-biodiversity-00_Biodiversity_Overview',
            'restoration-playbook/biodiversity/restoration-playbook-biodiversity-01_Assess_Biodiversity',
            'restoration-playbook/biodiversity/restoration-playbook-biodiversity-02_Restore_Habitats',
            'restoration-playbook/biodiversity/restoration-playbook-biodiversity-03_Create_Protected_Areas',
            'restoration-playbook/biodiversity/restoration-playbook-biodiversity-04_Manage_Invasive_Species',
            'restoration-playbook/biodiversity/restoration-playbook-biodiversity-05_Reintroduce_Lost_Species',
            'restoration-playbook/biodiversity/restoration-playbook-biodiversity-06_Monitor_Biodiversity',
          ],
        },
        {
          type: 'category',
          label: 'Community Engagement',
          items: [
            'restoration-playbook/community_engagement/restoration-playbook-community_engagement-00_Community_Engagement_Overview',
            'restoration-playbook/community_engagement/restoration-playbook-community_engagement-01_Identify_Stakeholders',
            'restoration-playbook/community_engagement/restoration-playbook-community_engagement-02_Communicate_Plans',
            'restoration-playbook/community_engagement/restoration-playbook-community_engagement-03_Educate_Community',
            'restoration-playbook/community_engagement/restoration-playbook-community_engagement-04_Involve_Community',
            'restoration-playbook/community_engagement/restoration-playbook-community_engagement-05_Share_Benefits',
            'restoration-playbook/community_engagement/restoration-playbook-community_engagement-06_Maintain_Communication',
          ],
        },
        {
          type: 'category',
          label: 'Reforestation',
          items: [
            'restoration-playbook/reforestation/restoration-playbook-reforestation-00_Reforestation_Overview',
            'restoration-playbook/reforestation/restoration-playbook-reforestation-01_Identify_Native_Species',
            'restoration-playbook/reforestation/restoration-playbook-reforestation-02_Source_Seedlings',
            'restoration-playbook/reforestation/restoration-playbook-reforestation-03_Prepare_Land',
            'restoration-playbook/reforestation/restoration-playbook-reforestation-04_Plant_Seedlings',
            'restoration-playbook/reforestation/restoration-playbook-reforestation-05_Monitor_Growth',
            'restoration-playbook/reforestation/restoration-playbook-reforestation-06_Long_Term_Management',
          ],
        },
        {
          type: 'category',
          label: 'Site Selection',
          items: [
            'restoration-playbook/site_selection/restoration-playbook-site_selection-00_Site_Selection_Overview',
            'restoration-playbook/site_selection/restoration-playbook-site_selection-01_Identify_Potential_Locations',
            'restoration-playbook/site_selection/restoration-playbook-site_selection-02_Evaluate_Land_Condition',
            'restoration-playbook/site_selection/restoration-playbook-site_selection-03_Estimate_Restoration_Potential',
            'restoration-playbook/site_selection/restoration-playbook-site_selection-04_Consider_Accessibility',
            'restoration-playbook/site_selection/restoration-playbook-site_selection-05_Research_Local_Regulations',
            'restoration-playbook/site_selection/restoration-playbook-site_selection-06_Contact_Landowners',
            'restoration-playbook/site_selection/restoration-playbook-site_selection-07_Visit_Sites',
            'restoration-playbook/site_selection/restoration-playbook-site_selection-08_Make_Shortlist',
          ],
        },
        {
          type: 'category',
          label: 'Soil Restoration',
          items: [
            'restoration-playbook/soil_restoration/restoration-playbook-soil_restoration-00_Soil_Restoration_Overview',
            'restoration-playbook/soil_restoration/restoration-playbook-soil_restoration-01_Assess_Soil_Health',
            'restoration-playbook/soil_restoration/restoration-playbook-soil_restoration-02_Add_Organic_Matter',
            'restoration-playbook/soil_restoration/restoration-playbook-soil_restoration-03_Reduce_Tillage',
            'restoration-playbook/soil_restoration/restoration-playbook-soil_restoration-04_Rotate_Crops',
            'restoration-playbook/soil_restoration/restoration-playbook-soil_restoration-05_Manage_Pests_Diseases',
            'restoration-playbook/soil_restoration/restoration-playbook-soil_restoration-06_Monitor_Soil_Health',
          ],
        },
        {
          type: 'category',
          label: 'Water Management',
          items: [
            'restoration-playbook/water_management/restoration-playbook-water_management-00_Water_Management_Overview',
            'restoration-playbook/water_management/restoration-playbook-water_management-01_Assess_Water_Needs',
            'restoration-playbook/water_management/restoration-playbook-water_management-02_Rainwater_Harvesting',
            'restoration-playbook/water_management/restoration-playbook-water_management-03_Build_Water_Storage_Structures',
            'restoration-playbook/water_management/restoration-playbook-water_management-04_Efficient_Irrigation',
            'restoration-playbook/water_management/restoration-playbook-water_management-05_Drought_Management',
            'restoration-playbook/water_management/restoration-playbook-water_management-06_Monitor_Water_Use',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      items: [
        'resources/quick-reference',
        'resources/roadmap',
        'resources/feature-wishlist',
      ],
    },
  ],
};

module.exports = sidebars;

