/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // For now, we'll use autogenerated sidebar until content is migrated
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Vision & Strategy',
      items: [
        'vision-strategy/executive-summary',
        'vision-strategy/project-vision',
        'vision-strategy/success-factors',
        'vision-strategy/current-status',
      ],
    },
    {
      type: 'category',
      label: 'Organization',
      items: [
        'organization/organizational-structure',
        'organization/governance',
        'organization/team-roles',
        'organization/legal-framework',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/restoration-methodology',
        'operations/technology-integration',
        'operations/challenges-solutions',
      ],
    },
    {
      type: 'category',
      label: 'Business',
      items: [
        'business/business-model',
        'business/financial-projections',
        'business/funding-strategy',
      ],
    },
    {
      type: 'category',
      label: 'Growth',
      items: [
        'growth/expansion-strategy',
        'growth/site-selection',
        'growth/adaptive-timeline',
        'growth/operations-action-plan',
        'growth/tiny-house-infrastructure',
      ],
    },
    {
      type: 'category',
      label: 'Performance',
      items: [
        'performance/risk-assessment',
        'performance/kpis',
      ],
    },
    {
      type: 'category',
      label: 'Engagement',
      items: [
        'engagement/marketing-communications',
      ],
    },
    {
      type: 'category',
      label: 'Learning',
      items: [
        'learning/case-studies',
      ],
    },
    {
      type: 'category',
      label: 'Restoration Playbook',
      items: [
        // Use autogenerated sidebar - Docusaurus will automatically include all files
        // This is simpler and more reliable than manually specifying each file
        {
          type: 'autogenerated',
          dirName: 'restoration-playbook',
        },
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      items: [
        'resources/quick-reference',
        'resources/roadmap',
        'resources/feature-wishlist',
      ],
    },
  ],
};

module.exports = sidebars;

