// @ts-check

/** Autogenerated from docs/ (built by scripts/sync-vnext.js). */
/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
const sidebars = {
  docsSidebar: [{ type: "autogenerated", dirName: "." }],
};

module.exports = sidebars;
