#!/usr/bin/env node
// Synthesis engine: classify the whole bookmark corpus by domain, distil each
// article to a one-line finding, group into per-domain evidence briefs, and run
// an assumption check (evidence gaps, low-verification sources, and articles
// that look like they challenge common assumptions).
const fs = require('fs');
const path = require('path');
const { walk, splitFrontmatter, frontField } = require('../lib/common');

const ROOT = path.resolve(__dirname, '../..');
const CORPUS = path.join(ROOT, 'research/bookmarks/Climate Change');
const OUT = path.join(ROOT, 'research/briefs');
const CITES = path.join(ROOT, 'research/citation_index.json');

const DOMAINS = [
  ['method/reforestation', ['tree', 'forest', 'reforest', 'planting', 'seedling', 'afforest', 'woodland', 'canopy', 'silvic']],
  ['method/soil', ['soil', 'fungi', 'mycorrhiz', 'compost', 'erosion', 'microb', 'peat', 'regenerative']],
  ['method/water', ['water', 'rain', 'drought', 'irrigation', 'river', 'groundwater', 'wetland', 'hydro', 'aquifer']],
  ['method/biodiversity', ['biodiversity', 'wildlife', 'habitat', 'rewilding', 'pollinator', 'bird', 'insect', 'fauna', 'species', 'extinction']],
  ['method/community', ['community', 'indigenous', 'stakeholder', 'volunteer', 'traditional knowledge']],
  ['site-and-land', ['land use', 'farmland', 'parcel', 'acquisition', 'land-use', 'abandoned land']],
  ['infrastructure', ['solar', 'off-grid', 'tiny house', 'renewable energy', 'building', 'tool']],
  ['organization', ['ngo', 'nonprofit', 'governance', 'legal', 'regulation', 'policy', 'eu ']],
  ['stewardship-handoff', ['trust', 'easement', 'commons', 'rights of nature', 'land tenure', 'succession']],
  ['funding', ['grant', 'funding', 'crowdfund', 'donor', 'philanthrop', 'finance for']],
  ['economics', ['carbon credit', 'carbon market', 'offset', 'revenue', 'cost', 'economic', 'payments for ecosystem', 'market']],
  ['growth-operations', ['scale', 'scaling', 'expansion', 'operations']],
  ['risk', ['wildfire', 'fire', 'pest', 'disease', 'flood', 'hazard', 'invasive', 'heatwave']],
  ['indicators', ['monitor', 'remote sensing', 'satellite', 'measure', 'indicator', 'citizen science']],
  ['learning', ['study finds', 'research shows', 'case study', 'lessons']],
];
const CAUTION = ['fail', 'backfire', 'myth', 'overestimat', 'overstat', 'struggl', 'unintended', 'ineffective', 'oversell', 'collaps', 'not enough', 'no benefit', "doesn't", 'cannot', 'contrad', 'declin'];

function classify(t) {
  t = t.toLowerCase();
  let best = 'general', score = 0;
  for (const [dom, kws] of DOMAINS) {
    let s = 0; for (const k of kws) if (t.includes(k)) s++;
    if (s > score) { score = s; best = dom; }
  }
  return best;
}
function tagsOf(front) {
  const m = front.match(/tags:\n((?:\s*-\s*.+\n?)+)/);
  return m ? m[1].split('\n').map(l => l.replace(/\s*-\s*/, '').trim()).filter(Boolean) : [];
}

let cited = {};
try { cited = JSON.parse(fs.readFileSync(CITES, 'utf8')); } catch (e) {}
const citedSet = new Set(Object.keys(cited));

const byDomain = {};
const caution = [], lowVerif = [];
let total = 0;
for (const f of walk(CORPUS)) {
  const { front } = splitFrontmatter(fs.readFileSync(f, 'utf8'));
  const id = frontField(front, 'entry_id'); if (!id) continue;
  total++;
  const title = frontField(front, 'title') || '';
  const topic = frontField(front, 'ai_main_topic') || '';
  const summary = frontField(front, 'ai_summary') || '';
  const type = frontField(front, 'article_type') || '';
  const verif = parseFloat(frontField(front, 'verification_score'));
  const needs = (frontField(front, 'needs_review') || '').toLowerCase() === 'true';
  const dom = classify([title, topic, tagsOf(front).join(' '), summary].join(' '));
  (byDomain[dom] ||= []).push({ id, title, topic, summary, type, verif, cited: citedSet.has(id) });
  const hay = (title + ' ' + summary).toLowerCase();
  if (CAUTION.some(c => hay.includes(c))) caution.push({ id, title, dom });
  if ((!isNaN(verif) && verif < 1.0) || needs) lowVerif.push({ id, title, verif: isNaN(verif) ? '?' : verif });
}

fs.mkdirSync(OUT, { recursive: true });
const link = id => `research/bookmarks/Climate%20Change/${id}.md`;
const clip = (s, n) => (s.length > n ? s.slice(0, n).replace(/\s+\S*$/, '') + '…' : s);

// index
const domsSorted = Object.keys(byDomain).sort((a, b) => byDomain[b].length - byDomain[a].length);
let idx = `# Evidence briefs — index\n\n${total} articles classified into ${domsSorted.length} domains. Each domain brief distils its articles to one-line findings. Generated by the synthesis engine.\n\n| Domain | Articles | Cited in docs | Uncited |\n|---|---|---|---|\n`;
for (const d of domsSorted) {
  const arr = byDomain[d]; const c = arr.filter(a => a.cited).length;
  idx += `| [${d}](${d.replace(/\//g, '__')}.md) | ${arr.length} | ${c} | ${arr.length - c} |\n`;
}
fs.writeFileSync(path.join(OUT, '_index.md'), idx);

// per-domain briefs
for (const d of domsSorted) {
  const arr = byDomain[d].sort((a, b) => (a.type || '').localeCompare(b.type || ''));
  let md = `# Evidence: ${d}\n\n${arr.length} articles. Distilled findings; **bold = already cited** in the docs.\n\n`;
  for (const a of arr) {
    const mark = a.cited ? '**[cited]** ' : '';
    const v = (!isNaN(a.verif) && a.verif < 1.0) ? ' _(needs verification)_' : '';
    const one = clip(a.summary || a.topic || a.title, 200);
    md += `- ${mark}[${clip(a.topic || a.title, 70)}](${link(a.id)})${a.type ? ` _(${a.type})_` : ''}${v} — ${one}\n`;
  }
  fs.writeFileSync(path.join(OUT, d.replace(/\//g, '__') + '.md'), md);
}

// assumptions report
let asm = `# Assumption check\n\nGenerated by the synthesis engine. For scientific hygiene, not a verdict.\n\n`;
asm += `## Evidence gaps (corpus rich, docs thin)\n\nDomains where we hold many articles but cite few — places our claims may be under-evidenced.\n\n`;
for (const d of domsSorted) {
  const arr = byDomain[d]; const c = arr.filter(a => a.cited).length;
  if (arr.length >= 8 && c <= 2) asm += `- **${d}** — ${arr.length} articles, ${c} cited.\n`;
}
asm += `\n## Articles that may challenge assumptions (${caution.length})\n\nReview these rather than rubber-stamp; they use language suggesting a method or claim fails, backfires, or is overstated.\n\n`;
for (const x of caution.slice(0, 60)) asm += `- [${clip(x.title, 80)}](${link(x.id)}) — _${x.dom}_\n`;
asm += `\n## Low-verification sources (${lowVerif.length})\n\nCite with care; flag as "needs verification" if used.\n\n`;
for (const x of lowVerif.slice(0, 40)) asm += `- [${clip(x.title, 80)}](${link(x.id)}) — score ${x.verif}\n`;
fs.writeFileSync(path.join(OUT, '_assumptions.md'), asm);

console.log(`Synthesis: ${total} articles -> ${domsSorted.length} domain briefs, ${caution.length} caution flags, ${lowVerif.length} low-verification.`);
