#!/usr/bin/env node
// State engine: render the project's execution state (state/state.yaml) into a
// readable snapshot, a publishable Status page (case/status.md), and a JSON
// copy for later dashboards. Project state only; the land has its own module.
const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const ROOT = path.resolve(__dirname, '../..');
const STATE = path.join(ROOT, 'state/state.yaml');
const OUT = path.join(ROOT, '_engines/_reports');

let s;
try { s = yaml.load(fs.readFileSync(STATE, 'utf8')) || {}; }
catch (e) { console.error('Could not read state/state.yaml:', e.message); process.exit(1); }

const eur = n => (n == null ? '?' : '€' + Number(n).toLocaleString('en-US'));
const d = v => (v instanceof Date ? v.toISOString().slice(0, 10) : v);

let md = `# Project status\n\n_Updated ${d(s.updated) || '?'} · phase: ${s.phase || '?'}_\n\n## Where things stand\n\n`;
if (s.people) md += `- People: ${s.people.founders ?? '?'} founders in ${s.people.location || '?'}, ${s.people.capacity || '?'}.\n`;
if (s.land) md += `- Land: ${s.land.status}${s.land.candidates ? ` (${s.land.candidates.join(', ')})` : ''}; target ${s.land.hectares_target || '?'} ha; ${s.land.secured ? 'secured' : 'not secured'}.\n`;
if (s.entity) md += `- Entity: ${s.entity.status}${s.entity.form ? ` (${s.entity.form})` : ''}.\n`;
if (s.funding) md += `- Funding: ${s.funding.started ? 'in progress' : 'not started'}. Raised ${eur(s.funding.raised_eur)}${s.funding.target_eur ? ` of ${eur(s.funding.target_eur)}` : ''}. Pipeline ${eur(s.funding.pipeline_eur)}.\n`;
if (s.restoration) md += `- On land: ${s.restoration.on_land ? 'yes' : 'no'}.\n`;
md += '\n';
if (s.funding && s.funding.target_eur) {
  const pct = Math.round(100 * (s.funding.raised_eur || 0) / s.funding.target_eur);
  const bar = '█'.repeat(Math.round(pct / 5)).padEnd(20, '░');
  md += `## Funding progress\n\n\`${bar}\` ${pct}% (${eur(s.funding.raised_eur)} / ${eur(s.funding.target_eur)})\n\n`;
}
if (s.funding && s.funding.approach) md += `Approach: ${s.funding.approach}\n\n`;
if (s.milestones) md += `## Milestones\n\n` + s.milestones.map(m => `- ${d(m.date)} — ${m.note}`).join('\n') + '\n\n';
if (s.next) md += `## Next\n\n` + s.next.map(x => `- ${x}`).join('\n') + '\n';

fs.mkdirSync(OUT, { recursive: true });
md += '\n[See the visual dashboard →](/dashboard)\n';
fs.writeFileSync(path.join(OUT, 'status.md'), md);
fs.writeFileSync(path.join(ROOT, 'state/status.json'), JSON.stringify(s, null, 2) + '\n');
// publishable page (flows through sync into the site under "Our Case")
const page = `---\ntitle: Status\nsidebar_position: 1\n---\n\n<!-- generated by engine:state from state/state.yaml; do not edit by hand -->\n\n` + md;
fs.writeFileSync(path.join(ROOT, 'case/status.md'), page);
console.log('State: snapshot + publishable case/status.md + state/status.json');
