/**
 * Sentry initialization for Docusaurus
 * 
 * This module initializes Sentry error tracking for the documentation site.
 * It runs in the browser and tracks JavaScript errors, performance, and user sessions.
 */

import * as Sentry from '@sentry/react';
import ExecutionEnvironment from '@docusaurus/ExecutionEnvironment';

function initSentry() {
  // Only initialize in browser (not during SSR)
  if (!ExecutionEnvironment.canUseDOM) {
    return;
  }

  // Get DSN from environment (injected at build time via webpack DefinePlugin)
  const dsn = process.env.SENTRY_DSN;

  if (!dsn) {
    console.log('ℹ️ [Sentry] DSN not configured, Sentry disabled');
    return;
  }

  // Get environment
  const environment = process.env.NODE_ENV || 'development';
  
  // Only track in production
  if (environment !== 'production') {
    console.log('ℹ️ [Sentry] Not in production mode, Sentry disabled');
    return;
  }

  try {
    // Log DSN status (without exposing the full DSN)
    const dsnPreview = dsn ? `${dsn.substring(0, 20)}...` : 'NOT SET';
    console.log('🔍 [Sentry] Initializing with DSN:', dsnPreview);
    console.log('🔍 [Sentry] Environment:', environment);
    console.log('🔍 [Sentry] Release:', process.env.SENTRY_RELEASE || 'not set');
    
    if (!dsn) {
      console.error('❌ [Sentry] DSN is empty - Sentry will not work!');
      return;
    }
    
    Sentry.init({
      dsn: dsn,
      environment: environment,
      
      // Performance monitoring
      tracesSampleRate: 0.1, // 10% of transactions
      
      // Session replay (optional - helps debug issues)
      replaysSessionSampleRate: 0.1, // 10% of sessions
      replaysOnErrorSampleRate: 1.0, // 100% of error sessions
      
      // Release tracking (set during build)
      release: process.env.SENTRY_RELEASE || undefined,
      
      // Integrations
      integrations: [
        Sentry.replayIntegration({
          maskAllText: true,
          blockAllMedia: true,
        }),
        Sentry.browserTracingIntegration(),
      ],
      
      // Filter out known non-critical errors
      ignoreErrors: [
        // Browser extensions
        'top.GLOBALS',
        'originalCreateNotification',
        'canvas.contentDocument',
        'MyApp_RemoveAllHighlights',
        'atomicFindClose',
        'fb_xd_fragment',
        'bmi_SafeAddOnload',
        'EBCallBackMessageReceived',
        // Network errors that are not actionable
        'NetworkError',
        'Network request failed',
        // Known browser issues
        'ResizeObserver loop limit exceeded',
        // Test errors: These are used by automated tests to verify Sentry is working.
        // The tests call captureException() to verify the function exists and works,
        // but we filter these out so they don't clutter the Sentry dashboard.
        'Test error for Sentry verification',
        'Test error from Playwright',
      ],
      
      // Filter out URLs from browser extensions
      denyUrls: [
        /extensions\//i,
        /^chrome:\/\//i,
        /^chrome-extension:\/\//i,
        /^moz-extension:\/\//i,
      ],
      
      // Set user context if available
      beforeSend(event, hint) {
        // Filter out test errors (including those with timestamps)
        // These errors are generated by automated tests to verify Sentry is working.
        // The tests verify that captureException() exists and can be called successfully,
        // but we don't want these test errors to appear in the Sentry dashboard.
        const isTestError = (text) => {
          if (!text) return false;
          return text.includes('Test error for Sentry verification') ||
                 text.includes('Test error from Playwright');
        };
        
        if (event.message && isTestError(event.message)) {
          return null; // Don't send test errors to Sentry
        }
        
        if (event.exception && event.exception.values) {
          for (const exception of event.exception.values) {
            if (exception.value && isTestError(exception.value)) {
              return null; // Don't send test errors to Sentry
            }
          }
        }
        
        // Add custom context
        event.tags = {
          ...event.tags,
          component: 'docusaurus-docs',
        };
        
        return event;
      },
    });

    // Expose Sentry on window for debugging (only in production)
    if (typeof window !== 'undefined') {
      window.Sentry = Sentry;
    }
    
    // Verify initialization (Sentry v10+ compatible)
    // getCurrentHub() was removed in v10, so we check if captureException is available
    if (typeof Sentry.captureException === 'function') {
      console.log('✅ [Sentry] Initialized successfully');
      console.log('✅ [Sentry] DSN configured:', dsnPreview);
      console.log('✅ [Sentry] Environment:', environment);
      console.log('✅ [Sentry] Release:', process.env.SENTRY_RELEASE || 'not set');
    } else {
      console.error('❌ [Sentry] Initialization completed but captureException not available!');
    }
  } catch (error) {
    // Sanitize error messages to prevent log injection (inline sanitization like in meilisearch-plugin.js)
    const sanitizedError = error ? String(error).replace(/[\r\n]/g, ' ').substring(0, 200) : 'Unknown error';
    const sanitizedMessage = error?.message ? String(error.message).replace(/[\r\n]/g, ' ').substring(0, 200) : 'No message';
    const sanitizedStack = error?.stack ? String(error.stack).replace(/[\r\n]/g, ' ').substring(0, 200) : 'No stack';
    console.error('❌ [Sentry] Initialization failed:', sanitizedError);
    console.error('❌ [Sentry] Error details:', sanitizedMessage, sanitizedStack);
  }
}

// Initialize when module loads
initSentry();

export default initSentry;

