#!/usr/bin/env node
/**
 * v-next docs sync
 *   template/   -> docs/model/        ("The Model")
 *   parameters/ -> docs/model/parameters/
 *   case/       -> docs/our-case/     ("Our Case")
 * Sidebar is autogenerated (sidebars.js); _category_.json sets labels/order.
 * Cross-tree links are rewritten so they resolve in the generated layout:
 *   ../template/    -> ../model/
 *   ../parameters/  -> ../model/parameters/
 * Manages only docs/model and docs/our-case (+ intro); legacy docs retired separately.
 */
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const DOCS = path.join(ROOT, 'docs');
const SRC = { model: path.join(ROOT, 'template'), parameters: path.join(ROOT, 'parameters'), case: path.join(ROOT, 'case') };
const MODEL_CATS = {
  'foundation': ['Foundation', 1], 'method': ['Method', 2], 'site-and-land': ['Site & land', 3],
  'infrastructure': ['Infrastructure & living', 4], 'organization': ['Organization', 5],
  'stewardship-handoff': ['Stewardship & handoff', 6], 'funding': ['Funding', 7], 'economics': ['Economics', 8],
  'growth-operations': ['Growth & operations', 9], 'risk': ['Risk', 10], 'indicators': ['Measuring progress', 11],
  'engagement': ['Engagement', 12], 'learning': ['Learning', 13], 'parameters': ['Parameters (bioregions)', 14],
};
const LANDING = `---
title: Eco Balance
slug: /
sidebar_position: 0
---

# Eco Balance

Restoring worn-out land into living habitat, and sharing how, so others can do the same.

We are two people bringing a few hectares of degraded land back to life, living on it, and handing it on in better shape than we found it. The work runs in two parts, kept deliberately separate.

## The Model

A reusable guide to this kind of restoration: the options, their trade-offs, and the evidence behind them. Fork it and start your own. → [Start here](model/foundation/why-restore-degraded-land.md) · [Try the explorer](/explorer)

## Our Case

What we are actually doing — the choices we have made and why, and where things stand right now. → [Our vision](our-case/vision.md) · [Status](our-case/status.md)

Everything is grounded in a working library of climate research, and what we learn on the ground feeds back into the model.
`;
function rmrf(p){ try{ if(fs.existsSync(p)) fs.rmSync(p,{recursive:true,force:true}); }catch(e){ console.warn('skip rm',p,e.code);} }
function ensure(p){ fs.mkdirSync(p,{recursive:true}); }
function pretty(n){ return n.replace(/[-_]/g,' ').replace(/\b\w/g,c=>c.toUpperCase()); }
function category(dir,label,position){ if(!fs.existsSync(dir))return; try{ fs.writeFileSync(path.join(dir,'_category_.json'),JSON.stringify({label,position},null,2)+'\n'); }catch(e){ console.warn('skip cat',dir,e.code);} }
function fixLinks(t){ return t.replace(/\]\(((?:\.\.\/)+)template\//g,']($1model/').replace(/\]\(((?:\.\.\/)+)parameters\//g,']($1model/parameters/').replace(/\]\(research\/bookmarks\/[^)]*?(\d{10,})\.md\)/g,'](/evidence#e$1)'); }
function copyMd(srcDir,destDir){ if(!fs.existsSync(srcDir))return 0; let n=0; for(const e of fs.readdirSync(srcDir,{withFileTypes:true})){ const s=path.join(srcDir,e.name),d=path.join(destDir,e.name); if(e.isDirectory())n+=copyMd(s,d); else if(e.name.endsWith('.md')){ ensure(destDir); fs.writeFileSync(d,fixLinks(fs.readFileSync(s,'utf8'))); n++; } } return n; }

ensure(DOCS); rmrf(path.join(DOCS,'model')); rmrf(path.join(DOCS,'our-case'));
try{ fs.writeFileSync(path.join(DOCS,'intro.md'),LANDING);}catch(e){ console.warn('intro write',e.code);}
const modelDir=path.join(DOCS,'model'); let m=0;
for(const e of fs.readdirSync(SRC.model,{withFileTypes:true})){ if(!e.isDirectory())continue; const dest=path.join(modelDir,e.name); m+=copyMd(path.join(SRC.model,e.name),dest); category(dest,...(MODEL_CATS[e.name]||[pretty(e.name),99])); }
m+=copyMd(SRC.parameters,path.join(modelDir,'parameters')); category(path.join(modelDir,'parameters'),...MODEL_CATS['parameters']); category(modelDir,'The Model',1);
const caseDir=path.join(DOCS,'our-case'); const c=copyMd(SRC.case,caseDir);
category(caseDir,'Our Case',2); category(path.join(caseDir,'decisions'),'Decisions',2); category(path.join(caseDir,'site-candidates'),'Site candidates',3);
console.log('Synced '+m+' model docs and '+c+' case docs.');
